INSERT INTO `genevalidator`.`roles` VALUES (1,'Administrador'),(2,'Usuario');
INSERT INTO `genevalidator`.`users` VALUES (1,1,'root','root','1234','root@gmail.com'),(2,2,'monica','monica','monica','monica@gmail.com'),(3,2,'prueba','prueba','prueba','prueba@gmail.com'),(4,2,'otro','otro','otro','otro@gmail.com');
INSERT INTO `genevalidator`.`menus` VALUES (1,0,'Usuarios',NULL,1,1,NULL),(2,1,'Crear usuario',NULL,2,0,'servletFormCreateUser'),(3,1,'Modificar usuario',NULL,3,0,''),(4,1,'Listar usuarios',NULL,4,0,'servletListUsers'),(5,1,'Borrar usuario',NULL,5,0,'servletDeleteUser'),(6,0,'Load Specie',NULL,6,0,'servletLoadSpecie'),(7,0,'Load Data',NULL,7,0,'servletLoadData'),(8,0,'Form Load Data',NULL,8,0,'servletFormLoadData'),(9,0,'Form Compare Genes',NULL,9,0,'sertvletFormCompareGenes'),(10,0,'Perfil',NULL,10,0,'servletFormPerfil');
INSERT INTO `genevalidator`.`roles_menus` VALUES (1,1,1),(2,1,2),(3,1,3),(4,1,4),(5,1,5),(6,1,6),(7,1,7),(8,1,8),(9,1,9),(10,1,10);
INSERT INTO `genevalidator`.`species` (`name_specie`) VALUES ('Arabidopsis_thaliana');
INSERT INTO `genevalidator`.`species` (`name_specie`) VALUES ('Caenorhabditis_elegans');
INSERT INTO `genevalidator`.`species` (`name_specie`) VALUES ('Drosophila_melanogaster');
INSERT INTO `genevalidator`.`species` (`name_specie`) VALUES ('Escherichia_coli');
INSERT INTO `genevalidator`.`species` (`name_specie`) VALUES ('Homo_sapiens');
INSERT INTO `genevalidator`.`species` (`name_specie`) VALUES ('Mus_musculus');
INSERT INTO `genevalidator`.`species` (`name_specie`) VALUES ('Rattus_norvegicus');
INSERT INTO `genevalidator`.`species` (`name_specie`) VALUES ('Saccharomyces_cerevisiae');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('Ensembl Gene ID', '1');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('Ensembl Protein ID', '1');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('Entrez Gene ID', '1');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('Gene Name', '1');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('RefSeq Protein ID', '1');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('RefSeq mRNA ID', '1');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('Uniprot ID', '1');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('Synonym', '1');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('Ensembl Gene ID', '2');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('Ensembl Protein ID', '2');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('Gene Name', '2');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('RefSeq Protein ID', '2');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('RefSeq mRNA ID', '2');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('Ensembl Protein ID', '2');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('Entrez Gene ID', '2');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('Uniprot ID', '2');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('Ensembl Gene ID', '3');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('Ensembl Protein ID', '3');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('Entrez Gene ID', '3');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('FlyBaseName Gene', '3');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('Gene Name', '3');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('RefSeq Protein ID', '3');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('RefSeq mRNA ID', '3');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('Uniprot ID', '3');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('Ensembl Gene ID', '4');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('Ensembl Protein ID', '4');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('Gene Name', '4');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('Synonym', '4');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('Ensembl Gene ID', '5');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('Ensembl Protein ID', '5');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('Entrez Gene ID', '5');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('Gene Name', '5');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('RefSeq Protein ID', '5');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('RefSeq mRNA ID', '5');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('Synonym', '5');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('Uniprot ID', '5');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('Ensembl Gene ID', '6');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('Ensembl Protein ID', '6');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('Entrez Gene ID', '6');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('Gene Name', '6');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('MGI ID', '6');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('RefSeq Protein ID', '6');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('RefSeq mRNA ID', '6');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('Synonym', '6');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('Uniprot ID', '6');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('Ensembl Gene ID', '7');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('Ensembl Protein ID', '7');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('Entrez Gene ID', '7');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('Gene Name', '7');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('RefSeq Protein ID', '7');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('RefSeq mRNA ID', '7');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('Synonym', '7');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('Uniprot ID', '7');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('Ensembl Gene ID', '8');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('Synonym', '8');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('Uniprot ID', '8');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('Entrez Gene ID', '8');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('Gene Name', '8');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('RefSeq Protein ID', '8');
INSERT INTO `genevalidator`.`nomenclatures` (`name_nomenclature`, `id_specie`) VALUES ('RefSeq mRNA ID', '8');
DELETE FROM `genevalidator`.`menus` WHERE (`id_menu` = '5');
DELETE FROM `genevalidator`.`menus` WHERE (`id_menu` = '3');
DELETE FROM `genevalidator`.`menus` WHERE (`id_menu` = '6');
DELETE FROM `genevalidator`.`menus` WHERE (`id_menu` = '8');
DELETE FROM `genevalidator`.`menus` WHERE (`id_menu` = '9');
INSERT INTO `genevalidator`.`menus` (`id_parent`, `name_menu`, `position`, `hasChilds`) VALUES ('0', 'Tool Data', '3', '1');
UPDATE `genevalidator`.`menus` SET `id_parent` = '11' WHERE (`id_menu` = '7');
UPDATE `genevalidator`.`menus` SET `id_menu` = '5' WHERE (`id_menu` = '11');
UPDATE `genevalidator`.`menus` SET `id_parent` = '5' WHERE (`id_menu` = '7');
UPDATE `genevalidator`.`menus` SET `position` = '5' WHERE (`id_menu` = '5');
UPDATE `genevalidator`.`menus` SET `action` = 'servletFormLoadData' WHERE (`id_menu` = '7');
UPDATE `genevalidator`.`menus` SET `icon` = 'fa fa-user' WHERE (`id_menu` = '1');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Abbott Pronk');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Abbott van Maris');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Aceituno Agosin');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Aghajan Huang');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Aguilera-Pronk');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Alper Stephanopoulos');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Amit Horovitz');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Ansari Morse');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Azzouz Collart');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Barbosa Mendes Ferreira');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Bessonov van der Merwe');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Bester Bauer');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Bodi Fray');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Boer Daran');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Boer Pronk');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Brauer Botstein');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Braun Young');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Busti Vanoni');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Caba Aubrecht');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Canelas Nielsen');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Chattopadhyay Tabor');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Chin Li');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Chiu Dawes');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Chu Herskowitz');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Chua Hughes');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Chujo Ishikawa');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Chumnanpuen Nielsen');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Cipollina de Winde');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Daran Lapujade Pronk');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('DeRisi Brown');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Dheur Javerzat');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Dymond Boeke');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Erlich Samson');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Fendt Sauer');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Ferea Rosenzweig');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Ferreira Menezes');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Fry Dedon');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Gasch Brown');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Ge Li');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Gibson Smart');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Gil Viegas');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Gonzalez Aguilera Aguilera');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Gross Winge');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Guan Culbertson');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Hazelwood Daran');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Hazelwood Dickinson');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Heer Sauer');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('HochwagenAmon');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Hong Nielsen');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Hughes Friend');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('James May');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Jin Wyrick');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Johansson Jacobson');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Knijnenburg Wessels');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Komili Silver');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Kresnowati Daran');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Lanza Alper');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Lee Lee');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Lee Marcotte');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Li Klevecz');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Li Smith');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Lin Green');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Liu Nielsen');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Lu Gerton');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Martin Bellis');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Matia Gonzalez Rodriguez Gabriel');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Medintz Thach');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Mitchell Pilpel');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Morillo Huesca Prado');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Ogawa Brown');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Orlando Haase');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Ouyang Sutter');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Parra Wyrick');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Pitkanen Renkonen');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Pizarro Agosin');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Rintala Penttila');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Rintala Ruohonen');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Roberts Friend');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Roberts Hudson');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Rodriguez-Lombardero Cerdan');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Ronald Kruglyak');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Rossouw Bauer');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Sabet Morse');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Salusjarvi Ruohonen');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Sanz Arroyo');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Shalem Pilpel');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Sheehan Hyman');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Simmons Kovacs Haase');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Simons Osbourn');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Singh Helm');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Snoek Daran');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Spellman Futcher');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Staschke Wek');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Sudarsanam Winston');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Sun Yuan');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Suzuki Iwahashi');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Tai Daran');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Takagi Kornberg');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Tauber Giorgini');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Tu McKnight');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Tyo Nielsen');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Urban Loewith');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Verwaal van Ooyen');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Vos Daran Lapujade');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Wade Auble');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Wells Blackshear');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Willis Moir');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Yarragudi Morse');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Yona Dahan');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Yu Morse');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Yvert Kruglyak');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Zhang Nielsen');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Zhu Bulyk');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Zhu Futcher');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('de Kok van Maris');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('van den Brink de Winde');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Tai Pronk');

--------------
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Faith Gardner');--118
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Babu Emili');--119
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Gagarinova Emili');--120
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Kumar Babu');--121
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Hu Emili');--122
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Nichols Gross');--123
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Rajgopala Uetz');--124
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('INTERPRO');--125
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('PFAM');--126

-------------------------------------------------------
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co-expression', '2008 Exp PCC', '118');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Genetic Interactions', '2011-Aggravating-GI-CE-MM', '119');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Genetic Interactions', '2011-Aggravating-GI-CE-RM', '119');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Genetic Interactions', '2011-Alleviating-GI-CE-MM', '119');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Genetic Interactions', '2011-Alleviating-GI-CE-RM', '119');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Genetic Interactions', '2011-CE-MM-PCC', '119');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Genetic Interactions', '2011-CE-RM-PCC', '119');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Genetic Interactions', '2011 A', '119');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Genetic Interactions', '2011 B', '119');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Genetic Interactions', '2014-Aggravating-GI-WG', '119');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Genetic Interactions', '2014-Alleviating-GI-WG', '119');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Genetic Interactions', '2014-WG-PCC', '119');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Genetic Interactions', '2014 A', '119');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Genetic Interactions', '2014 B', '119');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Genetic Interactions', '2016 A', '120');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Genetic Interactions', '2016 B', '120');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Genetic Interactions', '2016 A', '121');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Genetic Interactions', '2016 B', '121');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Other', '2009-GC-Int', '122');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Other', '2011-Gene-Gene-PCC', '123');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Physical Interactions', '2009-PPI', '122');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Physical Interactions', '2014-Y2H-PPI', '124');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Shared protein domains', '', '125');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Shared protein domains', '', '125');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('1', '5');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('2', '5');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('3', '5');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('4', '5');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('5', '5');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('6', '5');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('7', '5');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('8', '5');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('9', '5');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('10', '5');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('11', '5');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('12', '5');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('13', '5');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('14', '5');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('15', '5');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('16', '5');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('17', '5');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('18', '5');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('19', '5');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('20', '5');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('21', '5');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('22', '5');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('23', '5');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('24', '5');

----------------------------------------
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('BIOGRID-SMALL-SCALE-STUDIES');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('IREF-BIND');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('IREF-BIOGRID');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('IREF-DIP');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('IREF-INTACT');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('IREF-SMALL-SCALE-STUDIES');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('PPI-mapped');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `id_author`) VALUES ('Physical_Interactions', '127');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `id_author`) VALUES ('Physical_Interactions', '128');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `id_author`) VALUES ('Physical_Interactions', '129');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `id_author`) VALUES ('Physical_Interactions', '130');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `id_author`) VALUES ('Physical_Interactions', '131');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `id_author`) VALUES ('Physical_Interactions', '132');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `id_author`) VALUES ('Physical_Interactions', '133');
INSERT INTO `genevalidator`.`species` (`id_specie`, `name_specie`) VALUES ('9', 'Dnio rerio');
UPDATE `genevalidator`.`species` SET `name_specie` = 'Danio rerio' WHERE (`id_specie` = '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('25', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('26', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('27', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('28', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('29', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('30', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('31', '9');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `id_author`) VALUES ('Shared protein domains', '125');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `id_author`) VALUES ('Shared protein domains', '126');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('32', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('33', '9');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `id_author`) VALUES ('Genetic Interactions', '127');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('34', '9');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Alon Gothilf');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Andreasen Tanguay');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Benner Robison');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Cameron Yurco');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Chen Heideman');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Craig Hitchcock');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Drew Robison');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Fish Srivastava');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Giraldez Schier');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Hofsteen Heideman');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Jopling Izpisua Belmonte');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Leacock Amatruda');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Leung Dowling');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Ma Schachner');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Mathew Tanguay');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Maves Tapscott');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('McCurley Callard');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Monnich Horsfield');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Okuda Kamachi');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Ozbudak Pourquie');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Packham Chico');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Park Sayler');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Qin Raymond');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Rhodes Horsfield');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Robison Hardy');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Rogers Wilhelm');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Sarmah Marrs');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Sarras Intine');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Shkumatava Bartel');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Sleep Izpisua Belmonte');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Small Jones');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Soni Pillai');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Storer Zon');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Stuckenholz Bahary');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Tilton Gallagher');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Toyama Dawid');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Weicksel Sagerstrom');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('White Zon');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Xiong Heideman');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2009', '134');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2006', '135');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2013', '136');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2005', '137');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2008', '138');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2008', '139');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2008', '140');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2008', '141');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2006', '142');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2013', '143');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2012', '144');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2012', '145');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2008', '146');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2012', '147');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2008', '148');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2009', '148');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2007', '149');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2010', '150');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2011', '151');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2010', '152');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2010', '153');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2009', '154');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2012', '155');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2009', '156');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2010', '157');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2008', '158');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2011', '159');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2013', '160');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2013 A', '161');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2013 B', '161');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2013 C', '161');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2009', '162');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2010', '163');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2009', '164');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2013', '165');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2013', '166');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2009', '167');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2008', '168');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2009', '169');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2013', '170');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2011 A', '171');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2011 B', '171');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2008', '172');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('35', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('36', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('37', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('38', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('39', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('40', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('41', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('42', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('43', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('44', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('45', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('46', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('47', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('48', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('49', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('50', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('51', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('52', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('53', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('54', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('55', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('56', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('57', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('58', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('59', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('60', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('61', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('62', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('63', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('64', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('65', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('66', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('67', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('68', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('69', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('70', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('71', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('72', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('73', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('74', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('75', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('76', '9');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('77', '9');
--------------------
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `id_author`) VALUES ('Shared protein domains', '125');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `id_author`) VALUES ('Shared protein domains', '126');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('78', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('79', '2');
UPDATE `genevalidator`.`authors` SET `name_author` = 'Aguilera Pronk' WHERE (`id_author` = '5');
UPDATE `genevalidator`.`authors` SET `name_author` = 'Rodriguez Lombardero Cerdan' WHERE (`id_author` = '80');
UPDATE `genevalidator`.`authors` SET `name_author` = 'BIOGRID SMALL SCALE STUDIES' WHERE (`id_author` = '127');
UPDATE `genevalidator`.`authors` SET `name_author` = 'IREF BIND' WHERE (`id_author` = '128');
UPDATE `genevalidator`.`authors` SET `name_author` = 'IREF BIOGRID' WHERE (`id_author` = '129');
UPDATE `genevalidator`.`authors` SET `name_author` = 'IREF DIP' WHERE (`id_author` = '130');
UPDATE `genevalidator`.`authors` SET `name_author` = 'IREF INTACT' WHERE (`id_author` = '131');
UPDATE `genevalidator`.`authors` SET `name_author` = 'IREF SMALL SCALE STUDIES' WHERE (`id_author` = '132');
UPDATE `genevalidator`.`authors` SET `name_author` = 'PPI mapped' WHERE (`id_author` = '133');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Other', '2010 Co citation', '59');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('80', '2');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Byrne Roy');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Ceron van den Heuvel');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Lehner Fraser');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `id_author`) VALUES ('Genetic Interactions', '127');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Genetic Interactions', '2007', '180');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Genetic Interactions', '2007', '181');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Genetic Interactions', '2010', '59');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Genetic Interactions', '2006', '182');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('81', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('82', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('83', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('84', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('85', '2');
-----------------------------
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Boulton Vidal');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Boxem Vidal');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Davy Vidal');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Gottschalk Schafer');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Lenfant Reboul');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Li Vidal');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Reboul Vidal');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Reece Hoyes Walhout');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Simonis Vidal');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Walhout Vidal');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Xin Bader');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Xin Thierry Mieg');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `id_author`) VALUES ('Physical_Interactions', '127');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Physical_Interactions', '2002', '196');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Physical_Interactions', '2008 A', '197');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Physical_Interactions', '2008 B', '197');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Physical_Interactions', '2001', '198');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Physical_Interactions', '2005', '199');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `id_author`) VALUES ('Physical_Interactions', '128');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `id_author`) VALUES ('Physical_Interactions', '129');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `id_author`) VALUES ('Physical_Interactions', '130');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `id_author`) VALUES ('Physical_Interactions', '131');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `id_author`) VALUES ('Physical_Interactions', '132');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Physical_Interactions', '2010 Protein interations', '59');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Physical_Interactions', '2010 T2H', '59');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Physical_Interactions', '2010', '200');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Physical_Interactions', '2004', '201');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Physical_Interactions', '2003', '202');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Physical_Interactions', '2013', '203');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Physical_Interactions', '2009', '204');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Physical_Interactions', '2000', '205');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Physical_Interactions', '2013', '206');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Physical_Interactions', '2009', '207');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('86', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('87', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('88', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('89', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('90', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('91', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('92', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('93', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('94', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('95', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('96', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('97', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('98', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('99', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('100', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('101', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('102', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('103', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('104', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('105', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('106', '2');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Baugh Hunter');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Baugh Sternberg');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Bond Hanover');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Calvert de Magalhaes');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Chen Hamza');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Clark Miska');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Dawe de Pomerai');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Estes Troemel');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Falk Morgan');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Fox Miller');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Friday Keiper');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Greer Brunet');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Grishok Sharp');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Grompone Ramon');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Honjoh Nishida');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Jans Meyer');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Kim Kimble');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Kirienko Fay');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Krajacic Lamitina');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Lewis Jackson');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Mair Dillin');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('McElwee Gems');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Menzel Steinberg');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Nargund Haynes');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Noble Kimble');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Phirke Swoboda');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Pietsch Sturzenbaum');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Rohlfing Lamitina');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Stuart Kim');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Sugi Mori');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Tabuchi Hagstrom');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Troemel Kim');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Von Stetina Miller');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Wang Corsi');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Wright Ciosk');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('Yanai Hunter');
INSERT INTO `genevalidator`.`authors` (`name_author`) VALUES ('van der Linden Sengupta');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2005', '208');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2009', '207');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2014', '210');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2016', '211');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2012', '212');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2010', '213');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2009', '214');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2010', '215');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2008', '216');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2007 A', '217');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2007 B', '217');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2015', '218');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2010', '219');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2008', '220');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2012', '221');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2009', '222');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2009', '223');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2010', '224');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2007', '225');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2009', '226');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2009', '227');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2011', '228');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2004', '229');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2012', '230');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2012', '231');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2016', '232');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2011', '233');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2012', '234');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2010', '235');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2003', '236');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2011', '237');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2011', '238');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2006', '239');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2007', '240');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2006', '241');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2011', '242');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2008', '243');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2010', '244');
INSERT INTO `genevalidator`.`iterations` (`name_iteration`, `year`, `id_author`) VALUES ('Co expression', '2010', '59');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('107', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('108', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('109', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('110', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('111', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('112', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('113', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('114', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('115', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('116', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('117', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('118', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('119', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('120', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('121', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('122', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('123', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('124', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('125', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('126', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('127', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('128', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('129', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('130', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('131', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('132', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('133', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('134', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('135', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('136', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('137', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('138', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('139', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('140', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('141', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('142', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('143', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('144', '2');
INSERT INTO `genevalidator`.`iterations_species` (`id_iteration`, `id_specie`) VALUES ('145', '2');
